import os
import datetime
import markdown as md_lib
from langchain.tools import tool

REPORTS_DIR = "reports"
os.makedirs(REPORTS_DIR, exist_ok=True)

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Financial Intelligence Report</title>
  <style>
    body {{
      font-family: 'Segoe UI', Arial, sans-serif;
      max-width: 860px; margin: 48px auto; padding: 0 24px;
      color: #1a1a2e; line-height: 1.75; background: #fafafa;
    }}
    h1 {{ color: #1a237e; border-bottom: 3px solid #1a237e; padding-bottom: 10px; }}
    h2 {{ color: #283593; border-bottom: 1px solid #c5cae9; padding-bottom: 6px; margin-top: 36px; }}
    h3 {{ color: #3949ab; }}
    table {{ border-collapse: collapse; width: 100%; margin: 16px 0; }}
    th, td {{ border: 1px solid #c5cae9; padding: 10px 14px; text-align: left; }}
    th {{ background: #e8eaf6; font-weight: 600; }}
    tr:nth-child(even) {{ background: #f3f4ff; }}
    ul, ol {{ padding-left: 1.4em; }}
    li {{ margin-bottom: 4px; }}
    strong {{ color: #1a237e; }}
    code {{ background: #eef; padding: 2px 6px; border-radius: 3px; font-size: 0.91em; }}
    blockquote {{ border-left: 4px solid #7986cb; margin: 0; padding: 8px 16px; background: #e8eaf6; border-radius: 0 4px 4px 0; }}
    .footer {{ margin-top: 48px; padding-top: 14px; border-top: 1px solid #ddd; color: #888; font-size: 0.82em; }}
  </style>
</head>
<body>
{body}
<div class="footer">Generated by Financial Intelligence Agent &nbsp;·&nbsp; {timestamp}</div>
</body>
</html>"""

@tool
def save_report_to_file(content: str) -> str:
    """Save a report as a styled HTML file in the reports/ folder. Provide the full Markdown report content as input. The file can be opened in any web browser."""
    try:
        timestamp = datetime.datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"{REPORTS_DIR}/report_{timestamp}.html"
        body = md_lib.markdown(content, extensions=["tables", "fenced_code", "nl2br"])
        html = _HTML_TEMPLATE.format(
            body=body,
            timestamp=datetime.datetime.now().strftime("%B %d, %Y at %H:%M"),
        )
        with open(filename, "w", encoding="utf-8") as f:
            f.write(html)
        return f"✅ Report saved to: {filename} — open in any web browser to view"
    except Exception as e:
        return f"Error saving report: {str(e)}"

@tool
def format_markdown_report(raw_data: str) -> str:
    """Format raw research and financial data into a clean, structured Markdown report with sections, headers, and bullet points."""
    from langchain_openai import ChatOpenAI
    from langchain_core.messages import HumanMessage
    try:
        llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)
        prompt = (
            "You are a professional financial analyst. Format the following raw data into a clean, "
            "professional Markdown report with clear sections: Executive Summary, Key Financial Data, "
            "Market Analysis, News Highlights, and Conclusion.\n\n"
            "Important formatting rules:\n"
            "- Always write numbers as digits, never as words (e.g. '$73,854' not 'seventy-three thousand')\n"
            "- Write calculations inline as simple expressions (e.g. '$1.64T × 0.8576 = €1.40T')\n"
            "- Do NOT use LaTeX, mathematical notation, square brackets, or formula syntax\n"
            "- Use bullet points and bold text for emphasis\n"
            "- Keep the tone professional but readable\n\n"
            f"Data:\n{raw_data}"
        )
        response = llm.invoke([HumanMessage(content=prompt)])
        return response.content
    except Exception as e:
        return f"Formatting error: {str(e)}"